In [8]:
import numpy as np

def dct_2d(image):
    """
    Compute the 2D DCT of an 8x8 image block.
    """
    N = 8
    dct = np.zeros((N, N))
    for u in range(N):
        for v in range(N):
            sum = 0.0
            for x in range(N):
                for y in range(N):
                    cosx = np.cos((2*x + 1) * u * np.pi / (2 * N))
                    cosy = np.cos((2*y + 1) * v * np.pi / (2 * N))
                    sum += image[x, y] * cosx * cosy
            alpha_u = 1 / np.sqrt(8) if u == 0 else 1 / np.sqrt(4)
            alpha_v = 1 / np.sqrt(8) if v == 0 else 1 / np.sqrt(2)
            dct[u, v] = alpha_u * alpha_v * sum / 4
    return dct

def quantize_dct(dct, quantization_matrix):
    """
    Quantize the DCT coefficients using the quantization matrix.
    """
    return np.round(dct / quantization_matrix)

def compute_quantized_dct(image, quantization_matrix):
    """
    Compute the quantized DCT coefficients for an 8x8 block of image.
    """
    dct = dct_2d(image)
    quantized_dct = quantize_dct(dct, quantization_matrix)
    return quantized_dct

# Example usage:
image = 255*np.random.rand(8, 8)  # Example 8x8 block of image with random pixel values
quantization_matrix = np.random.randint(1, 50, (8, 8))  # Example 8x8 quantization matrix

quantized_dct = compute_quantized_dct(image, quantization_matrix)
print(image)
print(quantization_matrix)
print("Quantized DCT Coefficients:\n",quantized_dct)

[[108.33996976 108.74768541 209.20794842   2.99655503 171.29534219
   18.60390913 137.42647379 111.56233827]
 [110.63855831  87.03774608  41.4926009  136.16504439  89.43980379
   18.71288593 167.12272992 201.74876854]
 [251.46534288 216.5846384   23.58590462  22.20079721 126.44093866
   60.36592995  45.66446987 251.12220999]
 [ 38.00519807  99.72450303 169.43569608 148.32753878 206.67479467
   55.95542442  89.87815016 188.03087094]
 [238.84456615 117.0585285   92.96951688  58.57678938 106.94186449
    3.15872643 202.72536655  26.08507268]
 [ 62.9182996  152.32027833 244.9324678   27.61950291  26.82171069
  215.91877596 126.17120897  70.86642434]
 [ 51.45235916 142.7137018   67.0102554  193.70952913 198.90708233
  199.13536166 238.00619521 214.5643971 ]
 [154.06002823 227.75008764 236.9719916    7.74427111 225.19830767
  180.5528156  230.09795298 105.32158046]]
[[ 5  5 40 46 49  8 24 13]
 [35 36 13 43 44 29 28 20]
 [26 40 34 37 39 48 17 46]
 [32  8 30 37 22 34 48 20]
 [14 35 35 39 20 29